name: gpassmanager
base: core18 # the base snap is the execution environment for this snap
version: "1.1.0"
summary: CommandLine Password Manager
description: |
  A Commandline application for managing your passwords securely.
    It's a very secure password manager.

grade: stable
confinement: strict

apps:
  gpassmanager:
    command: gpassmanager

parts:
  gpassmanager:
    plugin: go
    source: .
    go-importpath: gpassmanager

plugs:
  gpassmanager-home:
    interface: home
