name: test
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go_version:
          - 1.17.x
          - 1.18.x
          - 1.19.x
          - 1.20.x
    name: Test with ${{ matrix.go_version }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go_version }}
      - name: Vet and test
        run: |
          go version
          go vet ./...
          go test ./...
